# Generated by Django 4.1.4 on 2022-12-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_student_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
